version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
