version: '3'

services:

  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jmon

  broker:
    image: redis:latest

    command: /bin/sh -c 'redis-server --appendonly yes --requirepass password'
    environment:
      REDIS_PASSWORD: password

  server:
    build:
      context: .
      dockerfile: Dockerfile.server

    environment:
      DB_TYPE: db+postgresql
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_NAME: jmon
      DB_PORT: 5432

      BROKER_TYPE: redis
      BROKER_USERNAME: ''
      BROKER_PASSWORD: 'password'
      BROKER_PORT: 6379
      BROKER_INSTANCE: 0

    links:
     - database
     - broker

  agent:
    build:
      context: .
      dockerfile: Dockerfile

    command: celery -A jmon worker

    links:
     - server
     - database
     - broker
