version: '3'

services:

  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

  broker:
    image: redis:latest

    command: redis-server --appendonly yes --requirepass $BROKER_PASSWORD
    env_file:
     - .env

  server:
    build: .

    command: python3 -u ./server.py
    env_file:
     - .env

    ports:
     - 5000:5000
    links:
     - database
     - broker

  scheduler:
    build: .
    command: celery -A jmon.app beat
    env_file:
     - .env
    links:
     - server
     - database
     - broker

  flower:
    build: .
    command: celery -A jmon.app flower
    ports:
     - 5555:5555
    env_file:
     - .env
    links:
     - server
     - database
     - broker

  agent:
    build: .
    command: celery -A jmon.app worker --concurrency=1
    env_file:
     - .env
    links:
     - server
     - database
     - broker
