version: '3'

services:

  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    env_file:
     - .env

  broker:
    image: redis:latest

    command: redis-server --appendonly yes --requirepass $BROKER_PASSWORD
    env_file:
     - .env

  server:
    build: .

    env_file:
     - .env

    links:
     - database
     - broker

  scheduler:
    build: .
    command: celery -A server beat
    env_file:
     - .env


  agent:
    build: .

    command: celery -A jmon worker

    env_file:
     - .env

    links:
     - server
     - database
     - broker
