"""Add column for trigger type for run

Revision ID: 1bacbaec2512
Revises: a0b3178469e8
Create Date: 2023-08-14 06:12:19.774339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1bacbaec2512'
down_revision = 'a0b3178469e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    clienttype_enum = postgresql.ENUM('SCHEDULED', 'MANUAL', name='runtriggertype', create_type=False)
    clienttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('run', sa.Column('trigger_type', sa.Enum('SCHEDULED', 'MANUAL', name='runtriggertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'trigger_type')
    # ### end Alembic commands ###
