"""Update run index for check and timestamp to include trigger type

Revision ID: e1155219bf75
Revises: a76dadf5ab0e
Create Date: 2023-08-17 06:41:25.823300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1155219bf75'
down_revision = 'a76dadf5ab0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('check_timestamp', table_name='run')
    op.create_index('check_trigger_type_timestamp', 'run', ['check_id', 'trigger_type', sa.text('timestamp ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('check_trigger_type_timestamp', table_name='run')
    op.create_index('check_timestamp', 'run', ['check_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###
